name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            USING_COVERAGE: "3.8"

        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]

        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: "Set up Python"
              uses: actions/setup-python@v2
              with:
                  python-version: "${{ matrix.python-version }}"

            - name: "Install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install black coverage coveralls flake8 flit mccabe mypy numpy pylint pytest tox tox-gh-actions

            - name: "Run tox targets for ${{ matrix.python-version }}"
              run: |
                  tox -e py

            - name: "Coveralls"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
                  COVERALLS_PARALLEL: true
              run: |
                  coveralls --service=github

    coveralls:
        name: "Indicate completion to coveralls.io"
        needs: build
        runs-on: ubuntu-latest
        container: python:3-slim

        steps:
            - name: "Finished"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  pip3 install --upgrade coveralls
                  coveralls --service=github --finish
